USE Application_DB
GO

--Bảng Tài Khoản
CREATE TABLE TAIKHOAN(
	TenDangNhap varchar(20) constraint PK_TAIKHOAN PRIMARY KEY,
	MatKhau varchar(20) NOT NULL,
	QuyenNguoiDung varchar(20) NOT NULL
)
go

--Bảng Giáo Viên
CREATE TABLE GIAOVIEN(
	MaGiaoVien varchar(20) constraint PK_GIAOVIEN PRIMARY KEY,
	HoTen nvarchar(50) NOT NULL,
	NgaySinh DATE CHECK(DATEDIFF(year, NgaySinh, GETDATE()) >= 18),
	GioiTinh nvarchar(20) NOT NULL, 
	DiaChi nvarchar(100) NOT NULL,
	SoDienThoai varchar(20) CHECK(len(SoDienThoai) = 10),
	Email varchar(50) NOT NULL,
	TenDangNhap varchar(20) CONSTRAINT FK_GIAOVIEN_TAIKHOAN FOREIGN KEY REFERENCES TAIKHOAN(TenDangNhap) ON DELETE SET NULL ON UPDATE CASCADE 
)
go

--Bảng Khóa Học
CREATE TABLE KHOAHOC(
	MaKhoaHoc varchar(20) constraint PK_KHOAHOC PRIMARY KEY,
	TenKhoaHoc nvarchar(50) NOT NULL
)
go

--Bảng Lớp Học
CREATE TABLE LOPHOC(
	MaLopHoc varchar(20) constraint PK_LOPHOC PRIMARY KEY,
	MaKhoaHoc varchar(20) constraint FK_LOPHOC_KHOAHOC FOREIGN KEY REFERENCES KHOAHOC(MaKhoaHoc) ON DELETE SET NULL ON UPDATE CASCADE,
	TenLopHoc nvarchar(50) NOT NULL,
	TongSoBuoiHoc INT CHECK(TongSoBuoiHoc > 0),
	HocPhi REAL CHECK(HocPhi >= 0)
)
go

--Bảng Phòng Học
CREATE TABLE PHONGHOC(
	MaPhongHoc varchar(20) constraint PK_PHONGHOC PRIMARY KEY,
	SoLuongChoNgoi INT CHECK(SoLuongChoNgoi > 0)
)	
go

--Bảng Danh Sách Nhóm
CREATE TABLE DANHSACHNHOM(
	MaNhomHoc varchar(20) constraint FK_DANHSACHNHOM_NHOMHOC FOREIGN KEY REFERENCES NHOMHOC(MaNhomHoc) ON DELETE CASCADE,
	MaHocVien varchar(20) constraint FK_DANHSACHNHOM_HOCVIEN FOREIGN KEY REFERENCES HOCVIEN(MaHocVien) ON DELETE CASCADE, 
	DiemLyThuyet REAL CHECK(DiemLyThuyet between 0 and 10) DEFAULT 0,
	DiemThucHanh REAL CHECK(DiemThucHanh between 0 and 10) DEFAULT 0,
	TrangThaiThanhToan BIT NOT NULL DEFAULT 0,
	TrangThaiCapChungChi BIT NOT NULL DEFAULT 0,
	CONSTRAINT PK_DANHSACHNHOM PRIMARY KEY (MaHocVien, MaNhomHoc)
)
go

--Bảng Phụ Trách
CREATE TABLE PHUTRACH(
	MaGiaoVien varchar(20) constraint FK_PHUTRACH_GIAOVIEN FOREIGN KEY REFERENCES GIAOVIEN(MaGiaoVien) ON DELETE CASCADE ON UPDATE CASCADE,
	MaKhoaHoc varchar(20) constraint FK_PHUTRACH_KHOAHOC FOREIGN KEY REFERENCES KHOAHOC(MaKhoaHoc) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT PK_PHUTRACH PRIMARY KEY (MaGiaoVien, MaKhoaHoc)
)
go

--Bảng Bảng Điểm Danh
CREATE TABLE BANGDIEMDANH(
	NgayHoc DATE constraint FK_BANGDIEMDANH_NGAYHOC FOREIGN KEY REFERENCES NGAYHOC(NgayHoc) ON DELETE CASCADE ,
	MaNhomHoc varchar(20) constraint FK_BANGDIEMDANH_NHOMHOC FOREIGN KEY REFERENCES NHOMHOC(MaNhomHoc) ON DELETE CASCADE ,
	MaHocVien varchar(20) constraint FK_BANGDIEMDANH_HOCVIEN FOREIGN KEY REFERENCES HOCVIEN(MaHocVien) ON DELETE CASCADE,
	HienDien BIT NOT NULL DEFAULT 0,
	CONSTRAINT PK_BANGDIEMDANH PRIMARY KEY (NgayHoc, MaNhomHoc, MaHocVien)
)
go